// Generated by CoffeeScript 1.6.3
(function() {
  var NewlinesAfterClasses;

  module.exports = NewlinesAfterClasses = (function() {
    function NewlinesAfterClasses() {}

    NewlinesAfterClasses.prototype.rule = {
      name: 'newlines_after_classes',
      value: 3,
      level: 'ignore',
      message: 'Wrong count of newlines between a class and other code',
      description: "Checks the number of newlines between classes and other        code"
    };

    NewlinesAfterClasses.prototype.lintLine = function(line, lineApi) {
      var context, ending, got, lineNumber;
      ending = lineApi.config[this.rule.name].value;
      if (!ending || lineApi.isLastLine()) {
        return null;
      }
      lineNumber = lineApi.lineNumber, context = lineApi.context;
      if (!context["class"].inClass && (context["class"].lastUnemptyLineInClass != null) && (lineNumber - context["class"].lastUnemptyLineInClass) !== ending) {
        got = lineNumber - context["class"].lastUnemptyLineInClass;
        return {
          context: "Expected " + ending + " got " + got
        };
      }
      return null;
    };

    return NewlinesAfterClasses;

  })();

}).call(this);
