// Generated by CoffeeScript 1.6.3
(function() {
  var NoEmptyParamList;

  module.exports = NoEmptyParamList = (function() {
    function NoEmptyParamList() {}

    NoEmptyParamList.prototype.rule = {
      name: 'no_empty_param_list',
      level: 'ignore',
      message: 'Empty parameter list is forbidden',
      description: "This rule prohibits empty parameter lists in function definitions.\n<pre>\n<code># The empty parameter list in here is unnecessary:\nmyFunction = () -&gt;\n\n# We might favor this instead:\nmyFunction = -&gt;\n</code>\n</pre>\nEmpty parameter lists are permitted by default."
    };

    NoEmptyParamList.prototype.tokens = ["PARAM_START"];

    NoEmptyParamList.prototype.lintToken = function(token, tokenApi) {
      var nextType;
      nextType = tokenApi.peek()[0];
      return nextType === 'PARAM_END';
    };

    return NoEmptyParamList;

  })();

}).call(this);
