// Generated by CoffeeScript 1.6.3
(function() {
  var NoImplicitParens;

  module.exports = NoImplicitParens = (function() {
    function NoImplicitParens() {}

    NoImplicitParens.prototype.rule = {
      name: 'no_implicit_parens',
      level: 'ignore',
      message: 'Implicit parens are forbidden',
      description: "This rule prohibits implicit parens on function calls.\n<pre>\n<code># Some folks don't like this style of coding.\nmyFunction a, b, c\n\n# And would rather it always be written like this:\nmyFunction(a, b, c)\n</code>\n</pre>\nImplicit parens are permitted by default, since their use is\nidiomatic CoffeeScript."
    };

    NoImplicitParens.prototype.tokens = ["CALL_START"];

    NoImplicitParens.prototype.lintToken = function(token, tokenApi) {
      return token.generated;
    };

    return NoImplicitParens;

  })();

}).call(this);
