// Generated by CoffeeScript 1.6.3
(function() {
  var NoTabs, indentationRegex,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  indentationRegex = /\S/;

  module.exports = NoTabs = (function() {
    function NoTabs() {}

    NoTabs.prototype.rule = {
      name: 'no_tabs',
      level: 'error',
      message: 'Line contains tab indentation',
      description: "This rule forbids tabs in indentation. Enough said. It is enabled by\ndefault."
    };

    NoTabs.prototype.lintLine = function(line, lineApi) {
      var indentation;
      indentation = line.split(indentationRegex)[0];
      if (lineApi.lineHasToken() && __indexOf.call(indentation, '\t') >= 0) {
        return true;
      } else {
        return null;
      }
    };

    return NoTabs;

  })();

}).call(this);
