// Generated by CoffeeScript 1.6.3
(function() {
  var render, ruleTemplate, rules, _;

  _ = require("underscore");

  rules = (require("./coffeelint")).RULES;

  render = function() {
    var rule, ruleName, rulesHTML, _i, _len, _ref, _results;
    rulesHTML = "";
    _ref = _.sortBy(_.keys(rules), (function(s) {
      return s;
    }));
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      ruleName = _ref[_i];
      rule = rules[ruleName];
      rule.name = ruleName;
      if (!rule.description) {
        rule.description = "[no description provided]";
      }
      _results.push(console.log(ruleTemplate(rule)));
    }
    return _results;
  };

  ruleTemplate = _.template("<tr>\n<td class=\"rule\"><%= name %></td>\n<td class=\"description\">\n    <%= description %>\n    <p><em>default level: <%= level %></em></p>\n</td>\n</tr>");

  render();

}).call(this);
